name: hello-world
on:
  push:
    branches:
    - prod
  pull_request:
jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: |
          echo "Hello Github Actions"
          echo "Build Number: $GITHUB_RUN_NUMBER"
          echo "Event Type: ${{ github.event_name }}"
